/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HuntRouteImport } from './routes/hunt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as PhotoSpotsRouteImport } from './routes/photo-spots'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as AnimalsIndexRouteImport } from './routes/animals.index'
import { Route as AnimalsAnimalIdRouteImport } from './routes/animals.$animalId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntRoute = HuntRouteImport.update({
  id: '/hunt',
  path: '/hunt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoSpotsRoute = PhotoSpotsRouteImport.update({
  id: '/photo-spots',
  path: '/photo-spots',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIndexRoute = AnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsAnimalIdRoute = AnimalsAnimalIdRouteImport.update({
  id: '/animals/$animalId',
  path: '/animals/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/facilities': typeof FacilitiesRoute
  '/favorites': typeof FavoritesRoute
  '/hunt': typeof HuntRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/photo-spots': typeof PhotoSpotsRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/visit': typeof VisitRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/api/chat': typeof ApiChatRoute
  '/animals/': typeof AnimalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/facilities': typeof FacilitiesRoute
  '/favorites': typeof FavoritesRoute
  '/hunt': typeof HuntRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/photo-spots': typeof PhotoSpotsRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/visit': typeof VisitRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/api/chat': typeof ApiChatRoute
  '/animals': typeof AnimalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/facilities': typeof FacilitiesRoute
  '/favorites': typeof FavoritesRoute
  '/hunt': typeof HuntRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/photo-spots': typeof PhotoSpotsRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/visit': typeof VisitRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/api/chat': typeof ApiChatRoute
  '/animals/': typeof AnimalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/facilities'
    | '/favorites'
    | '/hunt'
    | '/login'
    | '/map'
    | '/photo-spots'
    | '/profile'
    | '/quiz'
    | '/search'
    | '/signup'
    | '/visit'
    | '/animals/$animalId'
    | '/api/chat'
    | '/animals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/facilities'
    | '/favorites'
    | '/hunt'
    | '/login'
    | '/map'
    | '/photo-spots'
    | '/profile'
    | '/quiz'
    | '/search'
    | '/signup'
    | '/visit'
    | '/animals/$animalId'
    | '/api/chat'
    | '/animals'
  id:
    | '__root__'
    | '/'
    | '/facilities'
    | '/favorites'
    | '/hunt'
    | '/login'
    | '/map'
    | '/photo-spots'
    | '/profile'
    | '/quiz'
    | '/search'
    | '/signup'
    | '/visit'
    | '/animals/$animalId'
    | '/api/chat'
    | '/animals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FavoritesRoute: typeof FavoritesRoute
  HuntRoute: typeof HuntRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PhotoSpotsRoute: typeof PhotoSpotsRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  VisitRoute: typeof VisitRoute
  AnimalsAnimalIdRoute: typeof AnimalsAnimalIdRoute
  ApiChatRoute: typeof ApiChatRoute
  AnimalsIndexRoute: typeof AnimalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunt': {
      id: '/hunt'
      path: '/hunt'
      fullPath: '/hunt'
      preLoaderRoute: typeof HuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-spots': {
      id: '/photo-spots'
      path: '/photo-spots'
      fullPath: '/photo-spots'
      preLoaderRoute: typeof PhotoSpotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/': {
      id: '/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AnimalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$animalId': {
      id: '/animals/$animalId'
      path: '/animals/$animalId'
      fullPath: '/animals/$animalId'
      preLoaderRoute: typeof AnimalsAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacilitiesRoute: FacilitiesRoute,
  FavoritesRoute: FavoritesRoute,
  HuntRoute: HuntRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PhotoSpotsRoute: PhotoSpotsRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  VisitRoute: VisitRoute,
  AnimalsAnimalIdRoute: AnimalsAnimalIdRoute,
  ApiChatRoute: ApiChatRoute,
  AnimalsIndexRoute: AnimalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
