/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as MapRouteImport } from './routes/map'
import { Route as SearchRouteImport } from './routes/search'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as AnimalsIndexRouteImport } from './routes/animals.index'
import { Route as AnimalsAnimalIdRouteImport } from './routes/animals.$animalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIndexRoute = AnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsAnimalIdRoute = AnimalsAnimalIdRouteImport.update({
  id: '/animals/$animalId',
  path: '/animals/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/facilities': typeof FacilitiesRoute
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/visit': typeof VisitRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/animals/': typeof AnimalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/facilities': typeof FacilitiesRoute
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/visit': typeof VisitRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/animals': typeof AnimalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/facilities': typeof FacilitiesRoute
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/visit': typeof VisitRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/animals/': typeof AnimalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/facilities'
    | '/favorites'
    | '/map'
    | '/search'
    | '/visit'
    | '/animals/$animalId'
    | '/animals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/facilities'
    | '/favorites'
    | '/map'
    | '/search'
    | '/visit'
    | '/animals/$animalId'
    | '/animals'
  id:
    | '__root__'
    | '/'
    | '/facilities'
    | '/favorites'
    | '/map'
    | '/search'
    | '/visit'
    | '/animals/$animalId'
    | '/animals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FavoritesRoute: typeof FavoritesRoute
  MapRoute: typeof MapRoute
  SearchRoute: typeof SearchRoute
  VisitRoute: typeof VisitRoute
  AnimalsAnimalIdRoute: typeof AnimalsAnimalIdRoute
  AnimalsIndexRoute: typeof AnimalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/': {
      id: '/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AnimalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$animalId': {
      id: '/animals/$animalId'
      path: '/animals/$animalId'
      fullPath: '/animals/$animalId'
      preLoaderRoute: typeof AnimalsAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacilitiesRoute: FacilitiesRoute,
  FavoritesRoute: FavoritesRoute,
  MapRoute: MapRoute,
  SearchRoute: SearchRoute,
  VisitRoute: VisitRoute,
  AnimalsAnimalIdRoute: AnimalsAnimalIdRoute,
  AnimalsIndexRoute: AnimalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
